# Generated by Django 5.1.1 on 2024-09-23 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('lesson', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coaches/')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренера',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('duration', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.CreateModel(
            name='CoachFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coach')),
            ],
            options={
                'verbose_name': 'Отзыв на тренера',
                'verbose_name_plural': 'Отзывы на тренера',
            },
        ),
        migrations.CreateModel(
            name='LessonCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_slots', models.IntegerField()),
                ('day_of_week', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coach')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
            ],
            options={
                'verbose_name': 'Расписание тренера',
                'verbose_name_plural': 'Расписание тренеров',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.subscription')),
            ],
            options={
                'verbose_name': 'Приобретенный абонемент',
                'verbose_name_plural': 'Приобретенные абонементы',
            },
        ),
        migrations.CreateModel(
            name='TicketToLessonCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('lesson_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessoncoach')),
            ],
            options={
                'verbose_name': 'Запись на тренеровку к тренеру',
                'verbose_name_plural': 'Записи на тренировку к тренеру',
            },
        ),
    ]
