# Generated by Django 5.1.1 on 2024-09-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contactform_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachfeedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/'),
        ),
    ]
